# How to announce beheadings, options are GLOBAL, LOCAL, DIRECT, or OFF
behead-announcement-mobs: 'LOCAL'
behead-announcement-players: 'GLOBAL'

# Replaces death messages if player behead announcement is GLOBAL
behead-announcement-replaces-death-message: true

# The messages used to announce beheading
message-beheaded: '&6${VICTIM}&r was decapitated'
message-beheaded-by-entity: '&6${VICTIM}&r was decapitated by &6${KILLER}&r'
message-beheaded-by-entity-with-item: '&6${VICTIM}&r was decapitated by &6${KILLER}&r'
message-beheaded-by-entity-with-item-named: '&6${KILLER}&r decapitated &6${VICTIM}&r using &7${ITEM}&r'
message-beheaded-item-display-format: '${RARITY}[${NAME}${RARITY}]'

# Whether to drop heads when not killed by a player
drop-for-nonplayer-kills: false

# Whether to drop heads if killed by projectile weapon from a player
# Only checked if player-kills-only is true
drop-for-ranged-kills: false

# Whether to drop heads for any death cause if last-damager is a player
# Only checked if player-kills-only is true
drop-for-indirect-kills: false

# Only drop player heads (you can also do this in "default chances" file
# by making all mobs except players have a 0% chance of dropping a head)
player-heads-only: false

# Only drop "simple" mob heads (one per EntityType), without any unique
# features based on mob traits or subtype; very boring, not recommended
simple-mob-heads-only: false

# Whether to keep entity heads synced with the latest vanilla textures
refresh-textures: true

# Whether to reset the item name for a head when refreshing its texture
refresh-item-names: false

# When a player changes their skin, should old heads be updated to the
# new texture? Note: to refresh, heads must be mined or dropped
update-on-skin-change: false

# Track mob spawn reasons (uses rate modifiers from spawn-cause-modifiers.txt)
track-mob-spawns: true

# Enable the mechanic where any mob killed by a charged creeper explosion
# will drop its head with 100% probability * the spawn-cause modifier
# This setting overrides "player-kills-only" (but not "player-heads-only")
# Note: In vanilla, each charged creeper explosion causes only 1 head drop,
# DropHeads mimics this behavior from version 3.3.0 onward
charged-creeper-drops: true

# A Minecraft easter egg is that mobs named 'Dinnerbone' or 'Grumm' are
# upside down.. If you want their heads to share this trait, set to true
drop-grumm-heads: true
show-grumm-in-tab-complete: false

# Enable plugin Updater (checks for new versions with new head textures)
# Note: Disable if your server console reports errors
update-plugin: false

# Run in debug mode (prints extra information to console)
debug-messages: true

# Shows information about a head when right-clicked by a player
head-click-listener: true
head-click-format-mobs: "&7[&6DropHeads&7]&f That's ${A} ${NAME} ${TYPE}"
head-click-format-players: "&7[&6DropHeads&7]&f That's ${NAME}'s Head"

# Saves lore of heads in GameProfile when placed (used by some other plugins)
# Only works for player-type heads, eg: won't work for minecraft:creeper_head
# WARNING: This feature is in BETA and is relatively untested
# NOTE: Lore currently gets lost when the head is broken by non-player means
save-custom-lore: false

# Only drop heads if the killer used an axe
must-use-axe: false

# (Optional) Whitelist of tools a player must be using for heads to drop
# If "must-use-axe" is enabled, this list will be ignored
# If empty, no special weapon/tool will be required to get heads
must-use:
#  - IRON_SWORD
#  - DIAMOND_AXE
#  - WOOD_HOE

# Drop chances are multiplied by this number for each level of looting
looting-mutliplier: 1.01

# This number is added to the drop chance for each level of looting
looting-addition: 0.0

# Use vanilla behavior (overrides all other settings) for wither skeletons
vanilla-wither-skeleton-looting-behavior: true

# Replaces Zombie_Pigmen heads with Zombified_Piglin heads in 1.16+
update-zombie-pigman-heads: true

# (Optional) Let certain tools have a higher chance of beheading
# The number is the percent increase in drop chance when using that tool
# Eg: 0.8 = 80% more likely, -0.1 = 10% less likely, 2.0 = +200%, etc.
specific-tool-modifiers:
  GOLDEN_AXE: 3
  DIAMOND_AXE: 1
  IRON_AXE: 0.8
  STONE_AXE: 0.5
  SHEARS: 2
  DIAMOND_SWORD: 0.2
  IRON_SWORD: 0.1

# (Optional) Modify head drop chance based on how long the mob has been alive
# Format is "X: V", where if the mob has been alive for X or more time, then
# the drop rate is increased by V percent (similar to above; can be negative)
time-alive-modifiers:
  0s: -0.9
  1m30s: -0.5
  5m: 0
  2h: 0.1
  1d: 2.0
  1w: 3.0
  30w6d11h55m33s: 10.0