name: DropHeads
main: net.evmodder.DropHeads.DropHeads
author: EvModder/EvDoc
description: Provides a wide assortment of mob heads
website: https://dev.bukkit.org/projects/dropheads
#3=major rewrite,
#5=merge "sheep head" and "white sheep head", prevent-head-placement, custom drop rate for mob sub-types, prefer-vanilla-heads, hollow-skeletal-skulls, nbt-copy-click, custom lore save + show mob type in lore fix, preserve comments in head-textures.txt, sub-perms for /spawnhead
version: 3.5
api-version: 1.13
softdepend: [HeadDatabase]

commands:
  spawnhead:
    description: Get a player or mob head
    usage: /gethead [name]
    aliases: [gethead,getskull,dhspawn,spawn-head,head,phspawn,skull]
    permission: dropheads.spawn
    permission-message: You do not have permission to do this.

  droprate:
    description: Check the drop rate for a head
    usage: /droprate <mob type>
    aliases: [headrate,headdropchance,dhrate,headchance]
    permission: dropheads.droprate
    permission-message: You do not have permission to do this.

  debug_all_heads:
    description: Place all heads into the world around the player
    usage: /debug_all_heads
    permission: dropheads.debug
    permission-message: You do not have permission to do this.

permissions:
  dropheads.canlosehead:
    description: Killing this entity can cause their head to drop
    default: true

  dropheads.canbehead:
    description: This entity will be able to get heads
    default: true

  dropheads.alwaysbehead:
    description: This entity will get heads 100% of the time, unless canlosehead is false
    default: false
    children:
      dropheads.canbehead: true

  dropheads.canplacehead:
    description: Permission to place down a head block, if disabled by default in the config
    default: op

  dropheads.clickinfo:
    description: Permission to see info about a head by clicking it
    default: true

  dropheads.spawn:
    description: Permission to use /spawnhead
    default: op
    children:
      dropheads.spawn.mobs: true
      dropheads.spawn.players: true
      dropheads.spawn.self: true
      dropheads.spawn.code: true
      dropheads.spawn.hdb: true

  dropheads.spawn.mobs:
    description: Permission to spawn in mob heads
    default: op

  dropheads.spawn.players:
    description: Permission to spawn in other players' heads
    default: op

  dropheads.spawn.self:
    description: Permission to spawn in your own head
    default: op

  dropheads.spawn.code:
    description: Permission to spawn in heads with custom texture codes
    default: op

  dropheads.spawn.hdb:
    description: Permission to spawn in HeadDatabase heads
    default: op

  dropheads.droprate:
    description: Permission to check head drop rates with a command
    default: op

  dropheads.debug:
    description: Permission to spawn all the heads in a big cube
    default: false