name: DropHeads
main: net.evmodder.DropHeads.DropHeads
author: EvModder/EvDoc/Evil_Witchdoctor
version: 3.2.8 #8=stable 1.14 release
api-version: 1.13

commands:
   spawnhead:
      description: Get a player or mob head
      usage: /gethead [name]
      aliases: [gethead,dhspawn,spawn-head,head,phspawn,skull]
      permission: evp.dropheads.spawn
      permission-message: You do not have permission to do this.

   debug_all_heads:
      description: Place all heads into the world around the player
      usage: /debug_all_heads
      permission: evp.dropheads.debug
      permission-message: You do not have permission to do this.

permissions:
   evp.dropheads.alwaysbehead:
      description: This player will get heads 100% of the time
      default: false

   evp.dropheads.canbehead:
      description: This player will be able to get heads
      default: true

   evp.dropheads.spawn:
      description: Permission to spawn heads with a command
      default: op

   evp.dropheads.debug:
      description: Permission to spawn all the heads in a big cube
      default: false